INSERT INTO beer_types VALUES (1,'ヱビス生ビール',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO beer_types VALUES (2,'ヱビス瓶ビール（小）',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO beer_types VALUES (3,'ヱビスジューシーエール樽生',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO beer_types VALUES (4,'ヱビスジューシーエール中瓶',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
