INSERT INTO categories VALUES (1,'恵比寿1丁目・渋谷東',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO categories VALUES (2,'恵比寿2〜4丁目・広尾',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO categories VALUES (3,'恵比寿西・代官山',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO categories VALUES (4,'恵比寿南',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO categories VALUES (5,'ビアカクテル',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
