INSERT INTO egp.beer_types VALUES (1,'ヱビス生ビール',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO egp.beer_types VALUES (2,'ヱビス瓶ビール（小）',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO egp.beer_types VALUES (3,'ヱビスジューシーエール樽生',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO egp.beer_types VALUES (4,'ヱビスジューシーエール中瓶',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO egp.beer_types VALUES (5,'ヱビスプレミアムブラック（小瓶）',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO egp.beer_types VALUES (6,'限定ヱビス「薫満つ」（10ℓ）1店舗につき限定10樽',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO egp.beer_types VALUES (7,'ヱビス瓶ビール（中）',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO egp.beer_types VALUES (8,'琥珀ヱビス樽生',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
